/// @arg lane
/// @arg canSwitchLane
/// @arg speed
/// @arg switchSpeed
/// @arg jumpHeight
/// @arg jumpSpeed
/// @arg fallSpeed
/// @arg attackType
/// @arg maxHP

_lane = argument0;
_canSwitchLane = argument1;
_speed = argument2;
_switchSpeed = argument3;
_jumpHeight = argument4;
_jumpSpeed = argument5;
_fallSpeed = argument6;
_attackType = argument7;
_maxHP = argument8; 