event_inherited();

_colRadius = (bbox_right - bbox_left)/2;
_colX = 0;
_colY = 0;
_lastCollisionY = 0;
_initialLane = 0;
_destroySelf = false;
_ignoreProjectiles = false;
_laneCrossing = false;
_isVertical = false;
_hasOrigin = true;
_isIgnoringCover = false;
_isPiercing = false;
_isDestructible = false;
_isLauncher = false;
_isUp = false;
_canDetonate = false;
_reachesGround = false;
_isLob = false;