KeyBindings();
Layout();
GlobalGeneral();
Items();
Abilities();
Weapons();
Attacks();

//Resolution();
room = rm_street_parallelBridges;

global.playerSpeed = 6;
global.playerSwitchSpeed = 6;
global.playerMaxJumpHeight = 180;
global.playerJumpSpeed = 6;
global.playerFallSpeed = 20;
global.playerMelee = false;
global.playerAbilityPoints = 3;
global.playerWeaponPoints = 3;
global.playerAttackPoints = 3;

global.laneCrossing = false;
global.isVertical = false;
global.isIgnoringCover = false;
global.isPiercing = false;
global.isDestructible = false;
global.isUp = false;
global.isLauncher = false;
global.isLob = true;
global.canDetonate = false;
global.hasSlowAura = false;
global.hasSpeedAura = false;
global.damage = 20;
global.rateOfFire = .8;
global.buildUpDuration = 0;
global.travelSpeed = 15;
global.travelDistance = view_wview[0] + 100;
global.knockBack = 1;
global.stunLength = 4;
global.direction = 0;


global.laneCrossing2 = false;
global.isVertical2 = false;
global.isIgnoringCover2 = false;
global.isPiercing2 = false;
global.isDestructible2 = false;
global.isUp2 = false;
global.isLauncher2 = false;
global.isLob2 = false;
global.canDetonate2 = false;
global.hasSlowAura2 = false;
global.hasSpeedAura2 = false;
global.damage2 = 20;
global.rateOfFire2 = .8;
global.buildUpDuration2 = 0;
global.travelSpeed2 = 15;
global.travelDistance2 = view_wview[0] + 100;
global.knockBack2 = 1;
global.stunLength2 = 4;
global.direction2 = 0;